// N2/atividade-pratica-02/aplicacao-web-react/blog-react/src/components/PostCard.jsx
export default function PostCard({ titulo, resumo }) {
  return (
    <div style={{ marginBottom: '40px' }}>
      <h3 style={{ color: '#2d5284', fontSize: '1.4rem', margin: '0 0 8px 0', fontWeight: 'bold' }}>
        {titulo}
      </h3>
      <p style={{ color: '#555', fontSize: '1rem', margin: '0', lineHeight: '1.5' }}>
        {resumo}
      </p>
    </div>
  );
}

// N2/atividade-pratica-02/aplicacao-web-vue.js/blog-vue/src/components/PostCard.vue
<template>
  <div class="post-card">
    <h3>{{ titulo }}</h3>
    <p>{{ resumo }}</p>
  </div>
</template>

<script setup>
defineProps(['titulo', 'resumo'])
</script>

<style scoped>
.post-card {
  margin-bottom: 40px;
}
h3 {
  color: #2d5284;
  font-size: 1.4rem;
  margin: 0 0 8px 0;
  font-weight: bold;
}
p {
  color: #555;
  font-size: 1rem;
  line-height: 1.5;
}
</style>
